ALTER TABLE users
    ADD COLUMN validated BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN approver BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN admin BOOLEAN NOT NULL DEFAULT FALSE;
