-- MySQL Script generated by MySQL Workbench
-- Sa 03 Sep 2022 23:37:44 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `vpm`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vpm`.`users` ;

CREATE TABLE IF NOT EXISTS `vpm`.`users` (
  `username` VARCHAR(15) NOT NULL,
  `VRC_id` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `enabled` TINYINT NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `VRC_id_UNIQUE` (`VRC_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vpm`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vpm`.`authorities` ;

CREATE TABLE IF NOT EXISTS `vpm`.`authorities` (
  `username` VARCHAR(45) NOT NULL,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`),
  CONSTRAINT `usernames`
    FOREIGN KEY (`username`)
    REFERENCES `vpm`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vpm`.`packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vpm`.`packages` ;

CREATE TABLE IF NOT EXISTS `vpm`.`packages` (
  `id` VARCHAR(256) NOT NULL,
  `author` VARCHAR(15) NOT NULL,
  `display_name` VARCHAR(512) NOT NULL,
  `description` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `package_author` (`author` ASC) VISIBLE,
  INDEX `package_displayname` (`display_name` ASC) VISIBLE,
  CONSTRAINT `package_author`
    FOREIGN KEY (`author`)
    REFERENCES `vpm`.`users` (`username`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vpm`.`package_versions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vpm`.`package_versions` ;

CREATE TABLE IF NOT EXISTS `vpm`.`package_versions` (
  `package` VARCHAR(256) NOT NULL,
  `version_major` INT UNSIGNED NOT NULL,
  `version_minor` INT UNSIGNED NOT NULL,
  `version_revision` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`package`, `version_major`, `version_minor`, `version_revision`),
  CONSTRAINT `package_ref`
    FOREIGN KEY (`package`)
    REFERENCES `vpm`.`packages` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `vpm`.`dependencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vpm`.`dependencies` ;

CREATE TABLE IF NOT EXISTS `vpm`.`dependencies` (
  `dependent` VARCHAR(256) NOT NULL,
  `version_major` INT UNSIGNED NOT NULL,
  `version_minor` INT UNSIGNED NOT NULL,
  `version_revision` INT UNSIGNED NOT NULL,
  `dependency` VARCHAR(256) NOT NULL,
  `dependency_version` VARCHAR(45) NOT NULL DEFAULT 'x.x.x',
  PRIMARY KEY (`dependent`, `version_major`, `version_minor`, `version_revision`, `dependency`),
  CONSTRAINT `dependent_ref`
    FOREIGN KEY (`dependent` , `version_major` , `version_minor` , `version_revision`)
    REFERENCES `vpm`.`package_versions` (`package` , `version_major` , `version_minor` , `version_revision`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
